### ISSUE TITLE
Switch ERC20 client to new casper-js-sdk 2.10 and follow new conventions

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-contracts-js-clients#13]
We need to modernize how erc20 client is written to follow new client's design (same as cep47 and cep78) 
* use `Contract` class built-in into `casper-js-sdk`
* deprecate [client-helper](https://github.com/casper-network/casper-contracts-js-clients/tree/master/packages/client-helper) - it's now part of the SDK and we don't want to maintain another package
* let @dylanireland know about changes
* release as `1.0.0`

**Comment by hoffmannjan** [comment]
if possible try to describe this client using new JSON format

**Comment by hoffmannjan** [comment]
Also upgrade the whole lib to be compatible with `webpack5`

**Comment by Levike34** [comment]
any updates for this?  I am still getting the 'can't find 'fs' module' error

**Comment by RitaMAllenCA** [comment]
@hoffmannjan can Ryo do this?
