### ISSUE TITLE
can't use `casper-erc20-js-client` module

### ISSUE THREAD

**Issue by rainbowemoji** [casper-network/casper-contracts-js-clients#20]
Hello, I'm developing DApp on Casper network.
when I installed casper-erc20-js-client library on next.js framework, an error occurred.
![image](https://user-images.githubusercontent.com/14852261/160912514-d3a68c61-4ae9-4fbb-ad1d-6aa5cc3a9aa3.png)
how can I fix this error?

**Comment by rainbowemoji** [comment]
it works for webpack4
seems not working for webpack 5

**Comment by Levike34** [comment]
I am still getting this same error...any updates??

**Comment by hoffmannjan** [comment]
We will plan to upgrade dependencies so it will work with webpack 5. Will come back to you soon ☺️

**Comment by gyroflaw** [comment]
closing this issue in favor of https://github.com/casper-network/casper-contracts-js-clients/issues/13
